export const ICONS = {
  loading: 'mingcute:loading-3-fill',
  check: 'solar:check-circle-bold',
  error: 'solar:sad-circle-bold',
  arrow_down: 'solar:alt-arrow-down-bold',
  arrow_left: 'solar:alt-arrow-left-bold',
  users: 'solar:users-group-rounded-bold',
  user: 'solar:user-rounded-bold',
  project: 'solar:lightbulb-bold',
  entry: 'solar:notes-bold',
  translation: 'solar:earth-bold',
  add: 'solar:add-circle-bold',
  edit: 'solar:pen-bold',
  upload: 'solar:upload-square-bold',
  delete: 'solar:trash-bin-2-bold',
  menu: 'solar:menu-dots-bold',
  message: 'solar:letter-bold',
  github: 'mdi:github',
  settings: 'solar:settings-bold',
  search: 'solar:magnifier-linear',
  language: 'solar:map-bold',
  theme: 'solar:pallete-2-bold',
  sun: 'solar:sun-2-bold',
  moon: 'solar:moon-bold',
  leave: 'solar:exit-bold',
  save: 'fluent:save-32-filled',
}
